# Use an official Python runtime as a parent image
FROM python:3.7-slim

# Set working directory
WORKDIR /app

# Install system dependencies for building Python packages 
RUN apt-get update && apt-get install -y \
    build-essential \
    libopencv-dev 


# Copy requirements and install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install matplotlib

# Copy the application code
COPY main.py /app/main.py

# Expose the port FastAPI will run on
EXPOSE 8000

# Run the FastAPI application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]