# Use an official Python runtime as a parent image
FROM python:3.7-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./AImonk/ /app

# Install packages
RUN pip install Flask==2.1.0 requests==2.26.0 Pillow

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable for Flask
ENV FLASK_APP=main.py

# Run the command to start the Flask application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]